add initial exchange artifacts for the ed-fi x finance lea extension …
Ed-Fi-Exchange-OSS/Finance-Model-LEA-Extensions pull request #1
Opened 2021-08-30 17:55 UTC by ggaronzik

…project

2021-09-07 14:38 UTC, blmeyers requested changes

2021-09-07 14:38 UTC, blmeyers commented on EdFiXFinanceLEA_ETL/README.md
> +This script loads locally-defined StaffCharacteristicDescriptors from SFUSD's staff roster. Two modifications are requried here:
```suggestion
This script loads locally-defined StaffCharacteristicDescriptors from SFUSD's staff roster. Two modifications are required here: 
```

2021-09-07 14:38 UTC, blmeyers commented on EdFiXFinanceLEA_ETL/README.md
> +This script initializes he fiscal year and Local Education Agency information. Before running locally, modify the FiscalYear (line 12) to match your desired fiscal year and the LEA Id (line 15) to ma
```suggestion
This script initializes the fiscal year and Local Education Agency information. Before running locally, modify the FiscalYear (line 12) to match your desired fiscal year and the LEA Id (line 15) to match your organization's Local Education Agency identifier in Ed-Fi.
```

2021-11-01 13:52 UTC, ggaronzik commented
@stephenfuqua, SFUSD has given us the go ahead to release these changes to the Ed-Fi Exchange. I believe I need someone from Ed-Fi to approve any pr requests. Do you have time to look this over?

Once approved and merged, I will create a release/tag and we should be good to go!

2021-11-02 13:42 UTC, stephenfuqua approved these changes

2021-11-02 13:42 UTC, merged